"""empty message

Revision ID: 1b09289c577b
Revises: 2a295c108d05
Create Date: 2023-01-05 12:21:26.623891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b09289c577b'
down_revision = '2a295c108d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_board_id_fkey', 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('card_board_id_fkey', 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###
